# Generated by Django 3.0.5 on 2020-04-09 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clienttype',
            old_name='type',
            new_name='client_type',
        ),
    ]
