# Generated by Django 3.0.5 on 2020-04-09 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200409_2123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pricetype',
            old_name='type',
            new_name='price_type',
        ),
    ]
