# Generated by Django 3.0.5 on 2020-04-09 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200409_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='pricetype',
            name='price_type',
            field=models.CharField(choices=[('HC', 'Хорека'), ('DR', 'Драфт'), ('HA', 'Акция Хорека'), ('DA', 'Драфт Хорека'), ('MR', 'Марченко')], default='HC', max_length=2),
        ),
    ]
