# Generated by Django 3.0.5 on 2020-04-09 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200409_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='inn',
            field=models.CharField(max_length=12),
        ),
    ]
