# Generated by Django 3.0.5 on 2020-04-13 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20200413_1628'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='date_created',
            new_name='creation_date',
        ),
    ]
