# Generated by Django 3.0.5 on 2020-05-02 06:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0010_auto_20200413_2200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='is_active',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='client',
            name='manager',
        ),
        migrations.AddField(
            model_name='client',
            name='client_ID',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='database',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='latitude',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='longitude',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='managers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='client',
            name='phone',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='price',
            name='database',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_type',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='client',
            name='price_type',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='price',
            name='price_type',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='price',
            unique_together=set(),
        ),
        migrations.DeleteModel(
            name='ClientType',
        ),
        migrations.DeleteModel(
            name='PriceType',
        ),
    ]
