# Generated by Django 3.0.5 on 2020-05-04 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20200504_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='client',
        ),
        migrations.AddField(
            model_name='visit',
            name='client_ID',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
