# Generated by Django 3.0.5 on 2020-05-04 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20200504_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='visit',
            name='processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='visit',
            name='status',
            field=models.SmallIntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='visit',
            name='payment',
            field=models.FloatField(default=-1),
        ),
    ]
