# Generated by Django 3.0.5 on 2020-05-06 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20200505_1611'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visit',
            old_name='delivered',
            new_name='invoice',
        ),
        migrations.AlterField(
            model_name='order',
            name='delivered_quantity',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered_quantity',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='recommended_quantity',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='stock_quantity',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='payment',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
