# Generated by Django 3.0.5 on 2020-05-06 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20200506_0929'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='stock_quantity',
            new_name='balance',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='delivered_quantity',
            new_name='delivered',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='ordered_quantity',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='recommended_quantity',
            new_name='recommend',
        ),
    ]
