# Generated by Django 3.0.5 on 2020-05-07 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20200506_0933'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visit',
            old_name='client_ID',
            new_name='client_INN',
        ),
    ]
