# Generated by Django 3.0.5 on 2020-05-08 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20200507_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='database',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
