# Generated by Django 3.0.5 on 2020-05-08 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20200508_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='payment_plan',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
