# Generated by Django 3.0.5 on 2020-05-16 07:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_visit_payment_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistQuestion',
            fields=[
                ('UUID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_type', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChecklistAnswer',
            fields=[
                ('UUID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ChecklistQuestion')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Visit')),
            ],
        ),
    ]
