# Generated by Django 3.0.5 on 2020-05-16 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_checklistanswer_checklistquestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='manager_ID',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
