# Generated by Django 3.0.5 on 2020-05-16 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20200516_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistanswer',
            name='answer1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='checklistanswer',
            name='answer2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='checklistquestion',
            name='text',
            field=models.TextField(default='default question text'),
            preserve_default=False,
        ),
    ]
