# Generated by Django 3.0.5 on 2020-05-18 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_auto_20200518_1138'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='checklistquestion',
            order_with_respect_to=None,
        ),
    ]
